### ISSUE TITLE
Running h2o.ai in Azure ML (Installing Java is a must)

### ISSUE THREAD

**Issue by mkrdip** [MicrosoftDocs/pipelines-azureml#12]
`mcr.microsoft.com/azureml/base:0.2.4` is pretty flat, so tried a few steps to install Java.

1) Adding a custom base [dockerfile](https://gist.github.com/mkrdip/130c66c908b1c0b714414659cac77001)

```yml
script: train.py
arguments: []
framework: Python
environment:
  python:
    userManagedDependencies: false
    interpreterPath: python
    condaDependenciesFile: train-env.yml
  docker:
    enabled: true
    baseDockerfile: Dockerfile
```

Returns error: 
> Output from dependency scanning: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

2) Add an argument to the docker. According to this [documentation](https://notebooks.azure.com/rfernand/projects/azureml-getting-started/html/tutorials/sklearn-mnist/aml_config/docker.runconfig) and [this one](https://docs.microsoft.com/en-us/azure/machine-learning/reference-azure-machine-learning-cli) as well, I can add an argument to the docker command. So, tried the following.

```
script: train.py
arguments: []
framework: Python
environment:
  python:
    userManagedDependencies: false
    interpreterPath: python
    condaDependenciesFile: config/train-conda.yml
  docker:
    enabled: true
    baseImage: mcr.microsoft.com/azureml/base:0.2.4
    arguments: ["--run","apt-get install default-jdk"] 
```
also `arguments: "apt-get install default-jdk"` like this. 

As there is no documentation about it, having issues installing Java on the environment. Looking for your help.

**Comment by mkrdip** [comment]
Got this working by creating a Custom Docker Image and putting it to the ACR tied to Azure ML workspace. If the docker image is in any other ACR then it needs to be specified like following, get the admin based (basic or standard ACR) or token-based (Premium ACR) username/password.

```yml
docker:
    baseImage: youracrname.azurecr.io/imagename:v1
    baseImageRegistry: {
            "address": "youracrname.azurecr.io",
            "username": "username",
            "password": "password"
          }
```

Closing this as my issue is resolved. I suggest updating the documentation on docker specification for `.runconfig` files.
